behaviors:
  PlaneMovement:
    trainer_type: ppo
    time_horizon: 128 # Typical range: 32 - 2048
    max_steps: 1e6 # Typical range: 5e5 - 1e7
    hyperparameters:
      learning_rate: 3e-4 # Typical range: 1e-5 - 1e-3
      batch_size: 128
      buffer_size: 4000
      num_epoch: 3
    network_settings:
      num_layers: 2
      hidden_units: 256
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    summary_freq: 50000